export const projects = [
  {
    title: "Water Cat",
    image: "./images/pic-1.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Pepe Chill",
    image: "./images/pic-2.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Old Fashion",
    image: "./images/pic-3.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Sunflower",
    image: "./images/pic-4.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Winter in Nowhere",
    image: "./images/pic-5.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Makima",
    image: "./images/pic-6.jpg",
    year: 2025,
    href: "../sample-project.html",
  },
  {
    title: "Liar",
    image: "./images/pic-7.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Will u be my gf?",
    image: "./images/pic-8.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Shy lilly",
    image: "./images/pic-9.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Water Ducky",
    image: "./images/pic-10.jpg",
    year: 2025,
    href: "./sample-project.html",
  },
  {
    title: "Пивка?",
    image: "./images/pic-11.jpg",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Unnatural",
    image: "./images/pic-12.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Steel flower",
    image: "./images/pic-13.jpg",
    year: 2025,
    href: "./sample-project.html",
  },
  {
    title: "Remember me?",
    image: "./images/pic-14.jpg",
    year: 2025,
    href: "./sample-project.html",
  },
  {
    title: "U better hide",
    image: "./images/pic-15.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "WTF?",
    image: "./images/pic-16.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "He is better than all of us",
    image: "./images/pic-17.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "It's kinda hot",
    image: "./images/pic-18.jpg",
    year: 2025,
    href: "./sample-project.html",
  },
  {
    title: "Music time",
    image: "./images/pic-19.jpg",
    year: 2026,
    href: "./sample-project.html",
  },
  {
    title: "Hear it? Smell it?",
    image: "./images/pic-20.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "HELP ME!",
    image: "./images/pic-21.jpg",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Rainy chess",
    image: "./images/pic-22.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Relax",
    image: "./images/pic-23.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Aestethic",
    image: "./images/pic-24.jpg",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Is it ok?",
    image: "./images/pic-25.jpg",
    year: 2026,
    href: "./sample-project.html",
  },
];
